# Changes here will be overwritten by Copier
_commit: c84857f
_src_path: git@github.com:pupil-labs/pl-template.git
author_email: info@pupil-labs.com
author_fullname: Pupil Labs GmbH
author_username: pupil-labs
copyright_license: MIT
debug_module: false
project_description: Library for connecting to Neon via USB
project_name: Neon USB
publish_to_pypi: true
python_package_distribution_name: pupil-labs-neon-usb
python_package_import_name: neon_usb
repository_name: pl-neon-usb
repository_namespace: pupil-labs
repository_provider: github.com
